name: Auto Build DSP7 system.

on:
  push:
    branches:
      - main     
jobs:
  build-all:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config: [dongshanpiseven_core_defconfig ]
    steps:
      - uses: actions/checkout@v2
        with:
          path: buildroot-external-dongshanpiseven
      
      - uses: actions/checkout@v2
        with:
          repository: bootlin/buildroot
          ref: st/2021.02
          path: buildroot
          
      - name: Install buildroot dependencies
        run: sudo apt install debianutils sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc git mtools
        
      - name: Configure Buildroot
        run: make -C buildroot BR2_EXTERNAL=../buildroot-external-dongshanpiseven O=../output ${{ matrix.config }}
        
      - name: Build Buildroot
        run: make -C buildroot BR2_EXTERNAL=../buildroot-external-dongshanpiseven O=../output
        
      - name: Build toolchain
        run: make -C buildroot BR2_EXTERNAL=../buildroot-external-dongshanpiseven O=../output prepare-sdk        
        
      - name: Compress sdcard.img
        run: gzip -9 output/images/sdcard.img
        
      - name: Store images
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config }}
          path: output/images/sdcard.img.gz
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: |
            output/images/${{ matrix.config }}-arm-buildroot-linux-gnueabihf_sdk-buildroot.tar.gz
            output/images/${{ matrix.config }}-sdcard.img.gz
            output/images/${{ matrix.config }}-tf-a-stm32mp157c-100ask-512d-v1.stm32
            output/images/${{ matrix.config }}-u-boot.stm32
            output/images/${{ matrix.config }}-uImage
            output/images/${{ matrix.config }}-stm32mp157c-100ask-512d-lcd-v1.dtb
          
